//! The bindings the Mac app calls, generated by UniFFI. The app embeds a
//! session host through `Song`: it reads the arrangement to draw, is told of
//! each change as it lands, and drives the transport. The app holds no model
//! logic: what it draws is computed here from the host's song.

pub mod view;

use aaw_host::client::Request;
use aaw_host::command::{Command, Origin};
use aaw_host::host::{self, Clock, Event, Options, Running};
use aaw_host::session::{Change, Doc};
use serde_json::{json, Value as Json};
use std::path::Path;
use std::sync::{Arc, Mutex, RwLock};
pub use view::{Arrangement, Touch};

uniffi::setup_scaffolding!();

/// The output buffer the app asks for, in frames.
const BUFFER: u32 = 128;

#[derive(Debug, uniffi::Error)]
pub enum SongError {
    Failed { message: String },
}

impl std::fmt::Display for SongError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            SongError::Failed { message } => f.write_str(message),
        }
    }
}

impl std::error::Error for SongError {}

impl From<String> for SongError {
    fn from(message: String) -> SongError {
        SongError::Failed { message }
    }
}

/// Who made a change.
#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum Who {
    User,
    Agent,
    External,
}

/// A change as the activity panel lists it.
#[derive(Clone, Debug, uniffi::Record)]
pub struct ChangeInfo {
    pub revision: u64,
    pub origin: Who,
    /// The command, such as `clip.move`.
    pub op: String,
    pub label: String,
    /// What else the command changed to keep references valid.
    pub also: Vec<String>,
    /// Unix time in seconds.
    pub time: f64,
}

impl From<&Change> for ChangeInfo {
    fn from(c: &Change) -> ChangeInfo {
        ChangeInfo {
            revision: c.revision,
            origin: match c.origin {
                Origin::User => Who::User,
                Origin::Agent => Who::Agent,
                Origin::External => Who::External,
            },
            op: c.op.clone(),
            label: c.label.clone(),
            also: c.also.clone(),
            time: c.time,
        }
    }
}

/// A new revision: what changed, the arrangement after it, and the objects
/// that differ from the revision before.
#[derive(Clone, Debug, uniffi::Record)]
pub struct Update {
    pub change: ChangeInfo,
    pub arrangement: Arrangement,
    pub touched: Vec<Touch>,
}

/// The transport, in beats.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct TransportView {
    pub playing: bool,
    /// Where play starts.
    pub cue: f64,
    pub loop_region: Option<LoopRegion>,
}

#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct LoopRegion {
    pub start: f64,
    pub length: f64,
}

#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct Playhead {
    pub playing: bool,
    pub beat: f64,
}

/// What the app is told as it happens. Calls arrive on the host's thread, in
/// order, and must return promptly.
#[uniffi::export(with_foreign)]
pub trait SongObserver: Send + Sync {
    /// The song changed, whoever changed it.
    fn changed(&self, update: Update);
    /// Play state, start position or loop changed, whoever changed it.
    fn transport(&self, transport: TransportView);
    /// song.yaml holds an external edit that does not load, or it was fixed.
    fn invalid(&self, error: Option<String>);
    fn warning(&self, message: String);
    /// The host has saved and shut down, as after `daw close`.
    fn closed(&self);
}

/// A song open in a session host inside this process. While it is open, `daw`
/// commands from other processes reach the same host through its socket.
#[derive(uniffi::Object)]
pub struct Song {
    running: RwLock<Option<Running>>,
    clock: Arc<Clock>,
    latest: Arc<Mutex<Option<Arrangement>>>,
}

fn locked<T>(m: &Mutex<T>) -> std::sync::MutexGuard<'_, T> {
    m.lock().unwrap_or_else(|e| e.into_inner())
}

#[uniffi::export]
impl Song {
    /// Opens `song.yaml` at `path` and becomes its host. Fails when the song
    /// does not load or another host has it open.
    #[uniffi::constructor]
    pub fn open(path: String, observer: Arc<dyn SongObserver>) -> Result<Arc<Song>, SongError> {
        let latest = Arc::new(Mutex::new(None));
        let shown = latest.clone();
        let mut previous: Option<Doc> = None;
        let options = Options {
            buffer: BUFFER,
            play: None,
            exit_on_stop: false,
            seconds: None,
            feed: false,
            prepare: true,
        };
        let running = host::spawn(Path::new(&path), options, move |event| match event {
            Event::Opened(doc) => {
                *locked(&shown) = Some(view::arrangement(&doc, 0));
                previous = Some(doc);
            }
            Event::Changed { change, doc } => {
                let arrangement = view::arrangement(&doc, change.revision);
                let touched = previous.as_ref().map(|p| view::touched(p, &doc)).unwrap_or_default();
                *locked(&shown) = Some(arrangement.clone());
                previous = Some(doc);
                observer.changed(Update {
                    change: ChangeInfo::from(&change),
                    arrangement,
                    touched,
                });
            }
            Event::Transport(t) => observer.transport(TransportView {
                playing: t.playing,
                cue: t.cue,
                loop_region: t.region.map(|(start, length)| LoopRegion { start, length }),
            }),
            Event::Invalid(error) => observer.invalid(error),
            Event::Warning(message) => observer.warning(message),
            Event::Closed => observer.closed(),
        })?;
        Ok(Arc::new(Song {
            clock: running.clock().clone(),
            running: RwLock::new(Some(running)),
            latest,
        }))
    }

    /// The arrangement of the latest revision.
    pub fn arrangement(&self) -> Arrangement {
        locked(&self.latest).clone().expect("the host reports the song before `open` returns")
    }

    /// Where the song is playing, straight from the audio thread; cheap enough
    /// to read every frame. None until the first play has opened the output.
    pub fn playhead(&self) -> Option<Playhead> {
        self.clock.now().map(|(playing, beat)| Playhead { playing, beat })
    }

    /// Plays from a beat, or from the start position.
    pub fn play(&self, from: Option<f64>) -> Result<(), SongError> {
        self.transport(json!({"op": "play", "from": from}))
    }

    pub fn stop(&self) -> Result<(), SongError> {
        self.transport(json!({"op": "stop"}))
    }

    /// Sets the start position; while playing, playback jumps there.
    pub fn locate(&self, beat: f64) -> Result<(), SongError> {
        self.transport(json!({"op": "locate", "at": beat}))
    }

    pub fn set_loop(&self, start: f64, length: f64) -> Result<(), SongError> {
        self.transport(json!({"op": "loop", "start": start, "length": length}))
    }

    pub fn clear_loop(&self) -> Result<(), SongError> {
        self.transport(json!({"op": "loop"}))
    }

    /// Saves and shuts the host down. Later calls fail; `daw` commands then
    /// run headless.
    pub fn close(&self) {
        let running = self.running.write().unwrap_or_else(|e| e.into_inner()).take();
        if let Some(r) = running {
            let _ = r.close();
        }
    }
}

impl Song {
    fn transport(&self, command: Json) -> Result<(), SongError> {
        let command: Command = serde_json::from_value(command).map_err(|e| e.to_string())?;
        let running = self.running.read().unwrap_or_else(|e| e.into_inner());
        let host = running.as_ref().ok_or_else(|| "The song is closed".to_string())?;
        host.request(Request {
            command,
            origin: Origin::User,
            expect: None,
        })?;
        Ok(())
    }
}
