//! The bindings the Mac app calls, generated by UniFFI. The app embeds a
//! session host through `Song`: it reads the arrangement to draw, is told of
//! each change as it lands, edits the song and drives the transport. The app
//! holds no model logic: what it draws is computed here from the host's song,
//! and its edits become the host's commands here.

pub mod edits;
pub mod library;
pub mod view;
pub mod waveform;

use aaw_host::client::Request;
use aaw_host::command::{Command, Origin};
use aaw_host::host::{self, Clock, Event, Options, Running};
use aaw_host::session::{Change, Doc};
pub use edits::{Edit, Row};
use serde_json::{json, Value as Json};
use std::path::Path;
use std::sync::{Arc, Mutex, RwLock};
pub use view::{Arrangement, Touch};
pub use waveform::Waveforms;

uniffi::setup_scaffolding!();

/// The output buffer the app asks for, in frames.
const BUFFER: u32 = 128;

#[derive(Debug, uniffi::Error)]
pub enum SongError {
    Failed { message: String },
}

impl std::fmt::Display for SongError {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            SongError::Failed { message } => f.write_str(message),
        }
    }
}

impl std::error::Error for SongError {}

impl From<String> for SongError {
    fn from(message: String) -> SongError {
        SongError::Failed { message }
    }
}

/// Who made a change.
#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]
pub enum Who {
    User,
    Agent,
    External,
}

/// A change as the activity panel lists it.
#[derive(Clone, Debug, uniffi::Record)]
pub struct ChangeInfo {
    pub revision: u64,
    pub origin: Who,
    /// The command, such as `clip.move`.
    pub op: String,
    pub label: String,
    /// What else the command changed to keep references valid.
    pub also: Vec<String>,
    /// Unix time in seconds.
    pub time: f64,
    /// The drag the change is part of. A drag's changes follow one another
    /// as one undo step, and each replaces the one before in the change log.
    pub gesture: Option<String>,
}

impl From<Origin> for Who {
    fn from(origin: Origin) -> Who {
        match origin {
            Origin::User => Who::User,
            Origin::Agent => Who::Agent,
            Origin::External => Who::External,
        }
    }
}

impl From<&Change> for ChangeInfo {
    fn from(c: &Change) -> ChangeInfo {
        ChangeInfo {
            revision: c.revision,
            origin: c.origin.into(),
            op: c.op.clone(),
            label: c.label.clone(),
            also: c.also.clone(),
            time: c.time,
            gesture: c.gesture.clone(),
        }
    }
}

/// A step that undo or redo would take, and who made it.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct HistoryStep {
    pub label: String,
    pub origin: Who,
}

impl HistoryStep {
    fn from(step: Option<(String, Origin)>) -> Option<HistoryStep> {
        step.map(|(label, origin)| HistoryStep {
            label,
            origin: origin.into(),
        })
    }
}

/// A new revision: what changed, the arrangement after it, the objects that
/// differ from the revision before, and what undo and redo would now do.
#[derive(Clone, Debug, uniffi::Record)]
pub struct Update {
    pub change: ChangeInfo,
    pub arrangement: Arrangement,
    pub touched: Vec<Touch>,
    pub undo: Option<HistoryStep>,
    pub redo: Option<HistoryStep>,
}

/// The transport, in beats.
#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct TransportView {
    pub playing: bool,
    /// Where play starts.
    pub cue: f64,
    pub loop_region: Option<LoopRegion>,
}

#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct LoopRegion {
    pub start: f64,
    pub length: f64,
}

#[derive(Clone, Debug, PartialEq, uniffi::Record)]
pub struct Playhead {
    pub playing: bool,
    pub beat: f64,
}

/// What the app is told as it happens. Calls arrive on the host's thread, in
/// order, and must return promptly.
#[uniffi::export(with_foreign)]
pub trait SongObserver: Send + Sync {
    /// The song changed, whoever changed it.
    fn changed(&self, update: Update);
    /// Play state, start position or loop changed, whoever changed it.
    fn transport(&self, transport: TransportView);
    /// song.yaml holds an external edit that does not load, or it was fixed.
    fn invalid(&self, error: Option<String>);
    fn warning(&self, message: String);
    /// The waveforms of a revision, after its `changed`: which audio each
    /// track has, and peaks the app has not been sent. Called on a thread of
    /// its own, in order.
    fn waveforms(&self, waveforms: Waveforms);
    /// The host has saved and shut down, as after `daw close`.
    fn closed(&self);
}

/// A song open in a session host inside this process. While it is open, `daw`
/// commands from other processes reach the same host through its socket.
#[derive(uniffi::Object)]
pub struct Song {
    running: RwLock<Option<Running>>,
    clock: Arc<Clock>,
    latest: Arc<Mutex<Option<Arrangement>>>,
    /// The latest revision, which edits are worked out from.
    doc: Arc<Mutex<Option<Doc>>>,
}

fn locked<T>(m: &Mutex<T>) -> std::sync::MutexGuard<'_, T> {
    m.lock().unwrap_or_else(|e| e.into_inner())
}

#[uniffi::export]
impl Song {
    /// Opens `song.yaml` at `path` and becomes its host. Fails when the song
    /// does not load or another host has it open.
    #[uniffi::constructor]
    pub fn open(path: String, observer: Arc<dyn SongObserver>) -> Result<Arc<Song>, SongError> {
        let latest = Arc::new(Mutex::new(None));
        let shown = latest.clone();
        let doc = Arc::new(Mutex::new(None::<Doc>));
        let current = doc.clone();
        let waveforms = waveform::Worker::new(observer.clone());
        let options = Options {
            buffer: BUFFER,
            play: None,
            exit_on_stop: false,
            seconds: None,
            feed: false,
            prepare: true,
        };
        let running = host::spawn(Path::new(&path), options, move |event| match event {
            Event::Opened(doc) => {
                *locked(&shown) = Some(view::arrangement(&doc, 0));
                *locked(&current) = Some(doc);
            }
            Event::Changed { change, doc, history } => {
                let arrangement = view::arrangement(&doc, change.revision);
                let previous = locked(&current).replace(doc.clone());
                let touched = previous.map(|p| view::touched(&p, &doc)).unwrap_or_default();
                *locked(&shown) = Some(arrangement.clone());
                observer.changed(Update {
                    change: ChangeInfo::from(&change),
                    arrangement,
                    touched,
                    undo: HistoryStep::from(history.undo),
                    redo: HistoryStep::from(history.redo),
                });
            }
            Event::Compiled { revision, program } => {
                if let Some(doc) = locked(&current).as_ref() {
                    waveforms.compiled(revision, &program, doc);
                }
            }
            Event::Transport(t) => observer.transport(TransportView {
                playing: t.playing,
                cue: t.cue,
                loop_region: t.region.map(|(start, length)| LoopRegion { start, length }),
            }),
            Event::Invalid(error) => observer.invalid(error),
            Event::Warning(message) => observer.warning(message),
            Event::Closed => observer.closed(),
        })?;
        Ok(Arc::new(Song {
            clock: running.clock().clone(),
            running: RwLock::new(Some(running)),
            latest,
            doc,
        }))
    }

    /// The arrangement of the latest revision.
    pub fn arrangement(&self) -> Arrangement {
        locked(&self.latest).clone().expect("the host reports the song before `open` returns")
    }

    /// Where the song is playing, straight from the audio thread; cheap enough
    /// to read every frame. None until the first play has opened the output.
    pub fn playhead(&self) -> Option<Playhead> {
        self.clock.now().map(|(playing, beat)| Playhead { playing, beat })
    }

    /// Makes an edit as the person, as one undo step, and returns the keys of
    /// what it made: a new track, or the copies of duplicated clips. The host
    /// refuses an edit that would leave the song invalid, and nothing changes.
    ///
    /// `gesture` names the drag the edit is part of. A drag's edits are one
    /// undo step, and the song is saved when they pause.
    pub fn edit(&self, edit: Edit, gesture: Option<String>) -> Result<Vec<u64>, SongError> {
        let mut commands = {
            let doc = locked(&self.doc);
            edits::commands(doc.as_ref().ok_or_else(closed)?, &edit)?
        };
        let command = match (commands.len(), edits::label(&edit, commands.len())) {
            (0, _) => return Ok(Vec::new()),
            (1, None) => commands.remove(0),
            (_, label) => json!({"op": "batch", "commands": commands, "label": label}),
        };
        Ok(edits::made(&self.request(command, gesture)?))
    }

    /// Undoes the last change, whoever made it.
    pub fn undo(&self) -> Result<(), SongError> {
        self.request(json!({"op": "undo"}), None).map(|_| ())
    }

    pub fn redo(&self) -> Result<(), SongError> {
        self.request(json!({"op": "redo"}), None).map(|_| ())
    }

    /// Tells the host what the person has selected, for `daw status` to
    /// report. Keys of objects that are gone are left out.
    pub fn select(&self, keys: Vec<u64>) -> Result<(), SongError> {
        let items: Vec<String> = {
            let doc = locked(&self.doc);
            let handles = &doc.as_ref().ok_or_else(closed)?.handles;
            keys.iter().filter(|k| handles.contains(k)).map(|k| aaw_host::tree::handle_text(*k)).collect()
        };
        self.request(json!({"op": "select", "items": items}), None).map(|_| ())
    }

    /// Plays from a beat, or from the start position.
    pub fn play(&self, from: Option<f64>) -> Result<(), SongError> {
        self.transport(json!({"op": "play", "from": from}))
    }

    pub fn stop(&self) -> Result<(), SongError> {
        self.transport(json!({"op": "stop"}))
    }

    /// Sets the start position; while playing, playback jumps there.
    pub fn locate(&self, beat: f64) -> Result<(), SongError> {
        self.transport(json!({"op": "locate", "at": beat}))
    }

    pub fn set_loop(&self, start: f64, length: f64) -> Result<(), SongError> {
        self.transport(json!({"op": "loop", "start": start, "length": length}))
    }

    pub fn clear_loop(&self) -> Result<(), SongError> {
        self.transport(json!({"op": "loop"}))
    }

    /// Saves and shuts the host down. Later calls fail; `daw` commands then
    /// run headless.
    pub fn close(&self) {
        let running = self.running.write().unwrap_or_else(|e| e.into_inner()).take();
        if let Some(r) = running {
            let _ = r.close();
        }
    }
}

fn closed() -> String {
    "The song is closed".into()
}

/// A MIDI number as a note name, such as `C3`, for a row of a pattern's notes.
#[uniffi::export]
pub fn note_name(midi: i32) -> String {
    aaw_model::rules::note_name(midi.into()).unwrap_or_default()
}

/// The host's reason for refusing a command, as a person reads it: the
/// model's validation errors without their header and type tags, each as
/// `where: what`.
pub fn plain(message: &str) -> String {
    let mut lines = message.lines();
    if !lines.next().is_some_and(|first| first.contains("validation error")) {
        return message.to_string();
    }
    let mut out: Vec<String> = Vec::new();
    let mut place: Option<&str> = None;
    for line in lines {
        if !line.starts_with(' ') {
            place = Some(line);
            continue;
        }
        let what = line.trim();
        let what = what.rfind(" [type=").map_or(what, |i| &what[..i]);
        let what = what.strip_prefix("Value error, ").unwrap_or(what);
        out.push(match place.take() {
            Some(place) => format!("{place}: {what}"),
            None => what.to_string(),
        });
    }
    out.join("; ")
}

impl Song {
    /// Sends the host a command as the person and waits for its answer.
    fn request(&self, command: Json, gesture: Option<String>) -> Result<Json, SongError> {
        let command: Command = serde_json::from_value(command).map_err(|e| e.to_string())?;
        let running = self.running.read().unwrap_or_else(|e| e.into_inner());
        let host = running.as_ref().ok_or_else(closed)?;
        let request = Request {
            gesture,
            ..Request::new(command, Origin::User)
        };
        Ok(host.request(request).map_err(|e| plain(&e))?)
    }

    fn transport(&self, command: Json) -> Result<(), SongError> {
        self.request(command, None).map(|_| ())
    }
}
